(()=>{"use strict";
/* ===== SHEET CONFIG (constants) ===== */
const A="1WN8151jGQjqbfO0Aj2tK-79yJ9gCD_z0DLCdxs_higg",B="1P935LlAZAwW6cAdLKj1LVqhnr3vwCB5_gxjpZsIsIQM",C="1WN8151jGQjqbfO0Aj2tK-79yJ9gCD_z0DLCdxs_higg",D=[{name:"Indices",range:"A:Z",optional:!1},{name:"Indices_Intl",range:"A:Z",optional:!0}];

/* ===== CSV ===== */
const E=(e,t,n)=>`https://docs.google.com/spreadsheets/d/${e}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(t)}&range=${encodeURIComponent(n)}&t=${Date.now()}`;
function F(e){if((e||"").trim().startsWith("<"))return{rows:[],isHtml:!0};const t=[];let n=[],r="",o=!1;for(let a=0;a<e.length;a++){const l=e[a];if(o){if(l!=='"')r+=l;else e[a+1]==='"'?(r+='"',a++):o=!1}else if(l==='"')o=!0;else if(l===",")n.push(r),r="";else if(l==="\n")n.push(r),t.push(n),n=[],r="";else l!=="\r"&&(r+=l)}return(r.length>0||n.length>0)&&(n.push(r),t.push(n)),{rows:t,isHtml:!1}}
async function G(e,t,n){const r=await fetch(E(e,t,n));if(!r.ok)throw new Error(`Sheet fetch failed: ${e}/${t} (${r.status})`);const o=await r.text(),{rows:a,isHtml:l}=F(o);if(l){const e=new Error("Sheet returned HTML (likely not shared/published)");e.code="HTML";throw e}if(!a.length)return[];const i=a[0].map(s=>s.replace(/^\uFEFF/,"").replace(/\u00A0/g," ").trim());return a.slice(1).filter(s=>s.some(x=>(x??"").toString().trim()!=="")).map(s=>Object.fromEntries(i.map((x,h)=>[x,(s[h]??"").toString().trim()])))}

/* ===== HELPERS ===== */
const H=(e,t)=>{for(const n of t){const r=e[n];if(r!=null&&String(r).trim()!=="")return r}const n=(t[0]||"").toLowerCase();for(const r of Object.keys(e))if(r.toLowerCase().includes(n)&&String(e[r]).trim()!=="")return e[r];return void 0};
const I=e=>{if(e==null)return NaN;const t=String(e).trim();if(!t)return NaN;const n=Number(t.replace(/[,%\s]/g,""));return Number.isFinite(n)?n:NaN};
const J=(e,t=2)=>e==null||e===""||!Number.isFinite(Number(e))?"—":Number(e).toLocaleString("en-IN",{maximumFractionDigits:t,minimumFractionDigits:t});
function K(e=""){const t=String(e).toLowerCase();if(/sensex|nifty\s?50|banknifty|nifty bank|nifty next 50|s&p\s?500|dow|nasdaq|ftse|dax|cac|nikkei|hang\s*seng|kospi|asx|sse|sti|msci world/.test(t))return"benchmark";if(/(midcap|smallcap|microcap|nifty\s?(100|200|500)|bse\s?(100|200|500)|top\s?(100|200))/.test(t))return"broad";return/(auto|it|fmcg|pharma|realty|metal|psu|pse|energy|media|infra|fin|bank)/.test(t)?"sectoral":"sectoral"}
function L(e){const t=(H(e,["Market","Region","Country"])||"").toString().toLowerCase();if(/india|nse|bse/.test(t))return"india";if(/us|united states|nyse|nasdaq|s&p/.test(t))return"us";if(/europe|eu|uk|ftse|dax|cac|stoxx/.test(t))return"europe";if(/asia|japan|nikkei|china|shanghai|shenzhen|hk|hang\s*seng|kospi|taiwan|australia|asx|singapore|sti|apac/.test(t))return"asia-pac";if(/global|world|acwi/.test(t))return"global";const n=(H(e,["Name","Index","Label"])||"").toString().toLowerCase();if(/sensex|nifty|bse/.test(n))return"india";if(/s&p\s?500|spx|dow|djia|nasdaq|ndx|comp/.test(n))return"us";if(/ftse|dax|cac|stoxx/.test(n))return"europe";if(/nikkei|hang\s*seng|kospi|asx|sse|sti|taiwan/.test(n))return"asia-pac";return/msci\s?world|acwi/.test(n)?"global":"global"}
function M(e){if(!e||!e.length)return"";const t=e.map(v=>I(v)).filter(v=>Number.isFinite(v));if(!t.length)return"";const n=100,r=30,o=2,a=Math.min(...t),l=Math.max(...t),i=(l-a)||1;return t.map((v,s)=>{const x=(s/(t.length-1))*n,h=r-o-((v-a)/i)*(r-2*o);return(s?" L":"M")+x.toFixed(2)+","+h.toFixed(2)}).join("")}
function N(e){const t=H(e,["Name","Index","Label"])||"—",n=I(H(e,["Value","Last","Close"])),r=I(H(e,["ChangePct","%Chg","Pct"])),o=(H(e,["Family","Type"])||K(t)).toString().toLowerCase(),a=L(e),l=(()=>{const s=Object.keys(e),x=s.find(y=>y.toLowerCase()==="spark_1d");if(x&&e[x])return String(e[x]);const h=H(e,["Spark"]);if(h)return String(h);const c=s.filter(y=>/^s\d+$/i.test(y.trim())).sort((y,w)=>Number(y.slice(1))-Number(w.slice(1)));return c.map(y=>e[y]).filter(Boolean).join(",")})(),i=l.split(",").map(y=>y.trim()).filter(Boolean);return{name:t,last:n,chgp:r,fam:o,market:a,sparkVals:i}}
function O(e,t){const n=`i${t}`,r=Number(e.chgp),o=Number.isFinite(r)&&r>=0?"#16a34a":"#dc2626";return`<div class="card p-5 sm:p-6 min-h-40"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="text-sm text-slate-600 truncate" title="${e.name}">${e.name}</p><p class="text-2xl font-bold mt-1 leading-tight tracking-tight whitespace-nowrap">${J(e.last,2)}</p></div><span id="pill-${n}" class="pill shrink-0">—</span></div><svg class="spark block w-full h-14 mt-3 pointer-events-none" viewBox="0 0 100 30" preserveAspectRatio="none" aria-hidden="true"><path id="spark-${n}" d="" stroke="${o}"/></svg><div class="mt-3 flex flex-wrap items-center gap-2 text-xs text-slate-500"><span class="capitalize">${e.market.replace("-"," ")}</span><span>•</span><span class="capitalize">${e.fam.replace("-"," ")}</span></div></div>`}
function P(e,t){const n=`i${t}`,r=M(e.sparkVals.map(I)),o=document.getElementById(`spark-${n}`);if(o&&r)o.setAttribute("d",r);const a=document.getElementById(`pill-${n}`),l=Number(e.chgp);if(!a)return;if(!Number.isFinite(l))a.textContent="—",a.style.background="rgba(107,114,128,.12)",a.style.color="#374151";else a.textContent=(l>=0?"+":"")+l.toFixed(2)+"%",a.style.background=l>=0?"rgba(34,197,94,.12)":"rgba(239,68,68,.12)",a.style.color=l>=0?"#16a34a":"#dc2626"}
function Q(e,t,n="right"){const r=document.getElementById(e);if(!r)return;r.className=`ticker ${n==='right'?'ticker-right':'ticker-left'} text-sm font-medium`;r.innerHTML="";[...t,...t].forEach(o=>{const a=document.createElement("span");a.textContent=o;r.appendChild(a)})}
function R(e){let t=document.getElementById("diagBanner");if(!t){t=document.createElement("div");t.id="diagBanner";t.className="w-full bg-amber-50 border-b border-amber-200 text-amber-800";t.innerHTML=`<div class="container py-2 text-[12px]">${e}</div>`;document.body.prepend(t)}else t.querySelector(".container").textContent=e,t.style.display="block"}
async function S(){try{const e=[];for(const t of D)try{const n=await G(B,t.name,t.range);e.push(...n)}catch(n){if(!t.optional)throw n;console.warn(`[optional] ${t.name} failed`,n)}if(!e.length)throw new Error("No data rows from new workbook");return{rows:e,source:"new"}}catch(e){console.warn("New workbook failed:",e.message||e);R("Using fallback indices (original sheet). Tip: publish the new workbook & set sharing to Anyone with the link.");const t=await G(C,"Indices","A:Z");return{rows:t,source:"fallback"}}}
function T(e){const t=document.getElementById("grid"),n=document.getElementById("emptyState");t.innerHTML="";if(!e.length){n.classList.remove("hidden");const r=document.getElementById("countInfo");r&&(r.textContent="0 indices");return}n.classList.add("hidden");const r=e.map(N);r.forEach((o,a)=>t.insertAdjacentHTML("beforeend",O(o,a)));r.forEach((o,a)=>P(o,a));const o=document.getElementById("countInfo");o&&(o.textContent=`${r.length} indices`)}
async function U(){const e=document.getElementById("year");e&&(e.textContent=(new Date).getFullYear());try{const t=await G(A,"Headlines","A:B"),n=t.filter(s=>/^top$/i.test((s.Section||"").toString())).map(s=>s.Text),r=t.filter(s=>/^bottom$/i.test((s.Section||"").toString())).map(s=>s.Text);Q("topTicker",n,"right");Q("bottomTicker",r,"left")}catch(t){console.warn("Headlines error",t)}const{rows:n,source:r}=await S();T(n);const o=new Date,a=document.getElementById("lastUpdated");a&&(a.textContent=`Updated ${o.toLocaleString("en-IN")} · Source: ${r==="new"?"new workbook":"fallback (original)"}`)}
U().catch(console.error);
})();
